sudo: required
services:
    - docker

before_install:
    - docker build -t ytaniguchi8/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ytaniguchi8/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-northeast-1" 
    app: "taniguchi-docker"
    env: "TaniguchiDocker-env-3"
    bucket_name: "elasticbeanstalk-ap-northeast-1-085107194442"
    bucket_path: "taniguchi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
